# Generated by Django 6.0.5 on 2026-05-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='raw_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль (для восстановления)'),
        ),
    ]
