# Generated by Django 6.0.5 on 2026-05-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Телефон/Email'),
        ),
    ]
