# Generated by Django 6.0.5 on 2026-06-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (Узб)'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics_uz',
            field=models.JSONField(blank=True, default=dict, verbose_name='Характеристики (Узб)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (Узб)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (Узб)'),
        ),
    ]
