# Generated by Django 6.0.5 on 2026-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_colors_alter_product_name_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics_uz',
            field=models.JSONField(blank=True, null=True, verbose_name='Характеристики (Узб)'),
        ),
    ]
