# Generated by Django 6.0.5 on 2026-06-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, help_text='Укажите цвет, если это фото конкретного цвета товара. Например: black, orange', max_length=100, null=True, verbose_name='Цвет (для фильтра)'),
        ),
        migrations.CreateModel(
            name='ProductDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ПО / Драйвера')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на скачивание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='store.product')),
            ],
            options={
                'verbose_name': 'Драйвер / ПО',
                'verbose_name_plural': 'Драйверы и ПО',
            },
        ),
    ]
