# Generated by Django 6.0.5 on 2026-06-11 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productimage_color_productdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdriver',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым, если это общее ПО для всех товаров', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='store.product'),
        ),
    ]
